DDC - A more modular approach
ska-sa/dc_sand pull request #17
Opened 2020-08-27 12:05 UTC by andrewvanderbyl

A more modular approach for the DDC and it's sub modules. Yes, the GPU won't be able to be tested at this level, but it allows the CPU side testing to be more thorough. At GPU level the DDC can be compared as a whole to the CPU 'golden measure'.

2020-08-27 13:09 UTC, gcallanan reviewed
The general structure of the DDC code is starting to take shape, 

I have mode some style comments and architectural comments. I think these should both be modified a bit before I can approve this pull request.

2020-08-27 13:09 UTC, gcallanan commented on feng/ddc/src/ddc.py
> +        # Method to generate a complex-valued CW vector
For my own interest, what do you mean by dither in this case? Are you toggling the LSB? Do we use this in the SKARAB DDC?

2020-08-27 13:09 UTC, gcallanan commented on feng/ddc/src/ddc.py
> +    def generate_real_cw(self, freq: float, dither: bool):
Is this for the mixer or for the input data? maybe say in the function docstring what the CW vector is for.

2020-08-27 13:09 UTC, gcallanan commented on feng/ddc/src/ddc.py
> +    def decode_8bit_to_10bit_to_float_data(self, data_8bit: np.ndarray):
Although, now that I think about it, I see how this maps to the SKARAB, the SKARAB separated all of these functions. My first instinct is still that having each of these as a separate classes may be premature optimization - its far simpler to implement these on the CPU than it ever was on the SKARAB.

2020-08-27 13:38 UTC, andrewvanderbyl commented on feng/ddc/src/decimator.py
> +class decimator:
Done

2020-08-27 13:40 UTC, andrewvanderbyl commented on feng/ddc/src/ddc.py
> +    def decode_8bit_to_10bit_to_float_data(self, data_8bit: np.ndarray):
This has been removed. Realised after I committed ddc.py that I had not saved the current version so a dated version was committed.

2020-08-27 13:43 UTC, andrewvanderbyl commented on feng/ddc/src/ddc.py
> +        # Method to generate a real-valued CW vector
Done

2020-08-27 13:45 UTC, andrewvanderbyl commented on feng/ddc/src/ddc.py
> +    def __init__(self, decimation_factor: int, center_freq: float, data: np.ndarray, num_samples: int, filter_coeffs: np.ndarray) -> None:
Done

2020-08-27 13:49 UTC, andrewvanderbyl commented on feng/ddc/src/ddc.py
> +        # Method to generate a complex-valued CW vector
Yes. This would allow for a very small amount of noise to be added. Usually 1 LSB.

2020-08-27 13:50 UTC, andrewvanderbyl commented on feng/ddc/src/ddc.py
> +    def generate_real_cw(self, freq: float, dither: bool):
It's for the mixer or test vector. It has been removed and can be instantiated as needed for whichever purpose it is required.

2020-08-27 13:53 UTC, andrewvanderbyl commented on feng/ddc/src/ddc.py
> +    def run_ddc(self, osc: np.ndarray, data: np.ndarray, filter_coeffs: np.ndarray, decimation_factor: int):
Noted and fixed.

2020-08-28 12:56 UTC, andrewvanderbyl commented on feng/ddc/src/ddc.py
> +    def decode_8bit_to_10bit_to_float_data(self, data_8bit: np.ndarray):
Done. Responded via commit 595a04abee151aa9b324ae10df0c19f39666a348

2020-08-28 12:56 UTC, andrewvanderbyl commented on feng/ddc/src/ddc.py
> +        # Method to generate a real-valued CW vector
Done. Responded via commit 595a04abee151aa9b324ae10df0c19f39666a348

2020-08-28 12:56 UTC, andrewvanderbyl commented on feng/ddc/src/ddc.py
> +    def __init__(self, decimation_factor: int, center_freq: float, data: np.ndarray, num_samples: int, filter_coeffs: np.ndarray) -> None:
Done. Responded via commit 595a04abee151aa9b324ae10df0c19f39666a348

2020-08-28 12:56 UTC, andrewvanderbyl commented on feng/ddc/src/ddc.py
> +    def run_ddc(self, osc: np.ndarray, data: np.ndarray, filter_coeffs: np.ndarray, decimation_factor: int):
Done. Responded via commit 595a04abee151aa9b324ae10df0c19f39666a348

2020-08-28 13:45 UTC, gcallanan requested changes
This implementation is looking very clean and neat. 

I have pointed out one or two things that I think need to be clarified. Furthermore I would like to get some clarity on the cwg class.

2020-08-28 13:45 UTC, gcallanan commented on feng/ddc/src/cwg.py
> +class CWGenerator:
Class name should not be abbreviated.

Looking at this class, it does not look like there is any data that needs to be persistent across functions. This file may not need to be a class. Instead it may be better to just have standalone functions:

i.e. instead of doing :

```
import cwg
cwgObject = CWGenerator()
cwgObject.generate_real_cw()
```
rather have it just as:
```
import cwg
cwg.generate_real_cw()
```

2020-08-28 13:45 UTC, gcallanan commented on feng/ddc/src/ddc.py
> +class DigitalDownConverter:
I like the current look of the DDC class. It feels very clean.

2020-08-28 13:45 UTC, gcallanan commented on feng/ddc/src/ddc.py
> +        filter_coeffs: np.ndarray of type float
The docstrings are very helpful. The one things that is not coming through clearly is if the arrays are real or complex. 

I was under the impression that the DDC used complex mixing and as such should produce complex values somewhere in the chain. If this is not the case then I need to brush up on my theory. If it is the case, then I would just like for the real/complex nature of the signal to be apparent in the comments.

Unless of course numpy does complex data types? This is not something I have looked into.

2020-08-28 13:45 UTC, gcallanan commented on feng/ddc/src/ddc.py
> +    def _bandpass_fir_filter(self, input_data: np.ndarray, filter_coeffs: np.ndarray) -> np.ndarray:
filter_coeffs is also defined in the class __init__() function. I think it should only be in one place.

2020-08-28 13:45 UTC, gcallanan commented on feng/ddc/src/ddc.py
> +            Array of input (8bit-packed) samples to be unpacked.
It may just be worth clarifying that these are ten bit samples packed into an 8 bit array. This comment makes it seem like they are 8-bit samples.

2020-08-28 13:45 UTC, gcallanan commented on feng/ddc/testing/test_ddc.py
> +def DDC_test():
Is it worth having a test where the tone is completely out of the band of interest? Then you could check that its not accidentally getting mixed into the signal?

2020-08-28 13:45 UTC, gcallanan commented on feng/ddc/testing/test_cwg.py
> +def CWG_test():
What is the purpose of the CWG test class? Is this used specifically for mixing?

2020-08-28 13:45 UTC, gcallanan commented on feng/ddc/src/cwg.py
> +    def generate_real_cw(
What is the purpose of the CW class? Is this the signal that the filtered data will be mixed with?

On the CPU/GPU it may be better to just generate the CW tone in the mixer function itself. 

This becomes specifically applicable in the GPU implementation as generating the CW tone separately will heavily impact the performance as loading the cw tone from global memory more than doubles memory bandwidth whereas generating it in the same kernel is essentially free(well the sin() and cos() functions are not the cheapest to implement - but they are waaaaay cheaper than a global memory access).

2020-08-31 05:23 UTC, gcallanan commented on feng/ddc/src/cwg.py
> +    def generate_real_cw(
Now that I think about it, it may be nicer to have the CW generate function as a separate method for the CPU implementation, especially considering that you want a real and complex CW generating. Just bear in mind that on the GPU, this function will be baked into the kernel. 

I do not think the CW generator needs its own set of tests.

2020-08-31 08:29 UTC, james-smith-za commented on feng/ddc/src/cwg.py
> +class CWGenerator:
@gcallanan has a point, but I think this is a matter of style more than anything else. I wouldn't let this issue prevent a merge.

2020-08-31 08:29 UTC, james-smith-za commented on feng/ddc/src/cwg.py
> +    def generate_real_cw(
Calculations in the CPU actually also benefit from reducing the number of memory accesses required. But for the purposes of P-O-C code we want things to be easier for humans, not necessarily easier for computers.

Every line of code needs to be tested. Don't write code if there's not a test for it, and the tests should be based on the requirements.

2020-08-31 08:29 UTC, james-smith-za commented on feng/ddc/src/ddc.py
> +        filter_coeffs: np.ndarray of type float
Numpy does do complex datatypes. Usually it's transparent, you can pass a real-valued or a complex-valued array to most of the numpy functions and the maths will be correct.

2020-08-31 08:29 UTC, james-smith-za commented on feng/ddc/testing/test_cwg.py
> +def CWG_test():
This is a test fixture, not a class. It is for repeatability between tests.

2020-08-31 08:29 UTC, james-smith-za commented on feng/ddc/testing/test_ddc.py
> +def DDC_test():
Ideally that kind of thing should be in response to a properly-fleshed-out requirement spec. But I think it's worth including for PoC code.

That being said, @andrewvanderbyl please avoid having the word "test" in a test-fixture's name. Maybe call it `DDC_fixture` or something.

2020-08-31 08:54 UTC, gcallanan commented on feng/ddc/src/cwg.py
> +    def generate_real_cw(
My thought here is that the CW generator functions are really only going to be used on the CPU test implementation. So having a test for them would in this case result in us having a test for a test? This seems like adding one layer too many to the test setup.

2020-08-31 12:33 UTC, andrewvanderbyl commented on feng/ddc/src/ddc.py
> +    def generate_real_cw(self, freq: float, dither: bool):
Pass is just a place-holder for now.

2020-08-31 12:34 UTC, andrewvanderbyl commented on feng/ddc/src/cwg.py
> +class CWGenerator:
Changed to be consistent and as clear as possible.

2020-08-31 12:41 UTC, andrewvanderbyl commented on feng/ddc/src/ddc.py
> +        filter_coeffs: np.ndarray of type float
Complex mixing is required and does produce complex-valued products. Have added more clarity to the doc string.

2020-08-31 12:42 UTC, andrewvanderbyl commented on feng/ddc/src/ddc.py
> +    def _bandpass_fir_filter(self, input_data: np.ndarray, filter_coeffs: np.ndarray) -> np.ndarray:
Removed. It is not only in the init. It is unlikely the filter coeffs will change mid-observation so can remain static when the object is instantiated.

2020-08-31 12:42 UTC, andrewvanderbyl commented on feng/ddc/src/ddc.py
> +            Array of input (8bit-packed) samples to be unpacked.
Done.

2020-08-31 12:50 UTC, andrewvanderbyl commented on feng/ddc/testing/test_ddc.py
> +def DDC_test():
'test' in this case replaced with fixture. See commit: f3a7faa8c3acf2e0989706ba2181d236b072e39b

2020-08-31 13:09 UTC, gcallanan commented
From my side, I am happy with the current state of the code.

I am not certain on the need for a test for the CW generating functions but I don't think its a make or break choice. If @andrewvanderbyl and @james-smith-za think it is necessary then I will defer to them.

If @james-smith-za  is happy with this then I think we can merge.

2020-08-31 13:10 UTC, gcallanan approved these changes

2020-09-02 06:41 UTC, merged