DDC - CPU implementation with unit tests
ska-sa/dc_sand pull request #18
Opened 2020-09-10 07:01 UTC by andrewvanderbyl

Ok, here is another PR. Added some unit tests and fleshed out methods in the DDC. Seems to work as expected, but gremlins may still exists. DDC still a work-in-progress.

2020-09-11 07:06 UTC, gcallanan reviewed
I have made few small comments that I would like addressed. Overall I think the unit tests are looking sane and reasonable. I have not confirmed that the logic is 100% correct. But I think this will become clear when we start comparing it to the GPU implementation.

Eventually we will need to expand them to have broader coverage(different FFT sizes) but I think that is not really top priority right now. Obviously the point of a pull request is to monitor changes is small bite sized increments, so this was reasonable point to do a pull requrest.

2020-09-11 07:06 UTC, gcallanan commented on feng/ddc/testing/test_ddc.py
> +        )
Being assertive is hard

2020-09-11 10:19 UTC, james-smith-za requested changes
I am happy overall with the concepts. It's just some details that need reworking.

I will do a PR to show you a few handy things that I think you might like.

2020-09-11 10:19 UTC, james-smith-za commented on feng/ddc/testing/test_cwg.py
> +    assert cw_channel[1][0] == expected_channel
Is this because you expect a lot of energy to be in the DC bin?

2020-09-11 10:19 UTC, james-smith-za commented on feng/ddc/testing/test_cwg.py
> +
I'm wondering about this. Is it just because of the tone frequency you have chosen?

2020-09-11 10:19 UTC, james-smith-za commented on feng/ddc/testing/test_ddc.py
> +        )
Since this is a unit test, I'd rather use an assert statement.

`assert len(ddc_channel) == 1, "Too many channels!"` I think is the syntax.

2020-09-11 10:19 UTC, james-smith-za commented on feng/ddc/testing/test_ddc.py
> +        )
as above, I would suggest reworking this as an assert statement rather than a value error.

2020-09-11 10:19 UTC, james-smith-za commented on feng/ddc/testing/test_ddc.py
> +    assert ddc_channel[0][0] == expected_translation_center_channel
I realise that this indexing is as a result of the weird, tuple-of-arrays output that `np.where` gives, but it annoys me. Doesn't look clean and easy to understand.

I would rather do 

```
above_threshold_channels = np.where(np.abs(ddc_fft) > channel_threshold)
assert len(above_threshold_channels) == 1
ddc_translation_center_channel = above_threshold_channels[1][0]
assert ddc_translation_center_channel == expected_translation_center_channel
```
or something like that. IMO it makes things a bit more explicit.

2020-09-11 10:19 UTC, james-smith-za commented on feng/ddc/testing/test_ddc.py
> +    data = [cw1[0] + cw2[0]]
This is another artefact of your strange decision to make lists with one array in them. It clearly works, but it looks clunky.

2020-09-11 10:19 UTC, james-smith-za commented on feng/ddc/testing/test_ddc.py
> +    expected_translation_positive_band_edge = 503
Ideally I think this should be calculated from the parameters given in the start of the test. This would make for easier parameterisation.

2020-09-11 10:19 UTC, james-smith-za commented on feng/ddc/testing/test_ddc.py
> +    assert dB_diff > 60
You may want to make that 60.0 just to make it explicitly a float.

I mean it should be okay, but Python can do weird things sometimes.

2020-09-11 10:21 UTC, james-smith-za commented on feng/ddc/testing/test_ddc.py
> +        )
https://docs.pytest.org/en/latest/assert.html#defining-your-own-explanation-for-failed-assertions

Though I seem to recall that there are simpler ways to do things.

2020-09-11 10:21 UTC, james-smith-za commented on feng/ddc/testing/test_ddc.py
> +        )
`len()` function is defined for np arrays and works in 1-D case. `np.size()` is better if you expect a possibly multi-dimensional array.

2020-09-11 10:22 UTC, james-smith-za commented on feng/ddc/testing/test_cwg.py
>      awgn_scale = 0
Parameterising unit tests is not as simple as you might think. If the hard-coding is all in one place for now I think it's fine.

2020-09-11 10:22 UTC, james-smith-za commented on feng/ddc/testing/test_cwg.py
> +    assert cw_channel[1][0] == expected_channel
I think the first is DC?

2020-09-11 11:36 UTC, andrewvanderbyl commented on feng/ddc/testing/test_ddc.py
> +    ddc_coeff_filename = "/home/avanderbyl/Git/dc_sand/feng/ddc/src/ddc_coeff_107MHz.csv"
Done. This is now in the same /src folder as the ddc.py.

2020-09-11 11:37 UTC, andrewvanderbyl commented on feng/ddc/src/cwg.py
> +    return [cwg + awgn]
Fixed. All other code changes required to support this change implemented.

2020-09-11 11:53 UTC, andrewvanderbyl commented on feng/ddc/testing/test_ddc.py
> +        )
Agreed. Changed to 'assert'.

2020-09-14 07:14 UTC, gcallanan commented
From my side I am happy with the current state of the repo. If @james-smith-za ' feedback has been addressed then I think we can merge.

2020-09-14 07:36 UTC, andrewvanderbyl commented on feng/ddc/testing/test_cwg.py
> +    assert cw_channel[1][0] == expected_channel
Fixed with change to the CW generation.

2020-09-14 07:39 UTC, andrewvanderbyl commented on feng/ddc/testing/test_ddc.py
> +        )
Agreed. Changed to 'assert'.

2020-09-14 07:54 UTC, andrewvanderbyl commented on feng/ddc/testing/test_ddc.py
> +        )
Agreed. Changed to 'assert'.

2020-09-14 07:54 UTC, andrewvanderbyl commented on feng/ddc/testing/test_ddc.py
> +        )
Agreed. Changed to 'assert'.

2020-09-14 07:57 UTC, andrewvanderbyl commented on feng/ddc/src/cwg.py
> +    return [cwg + awgn]
Done.

2020-09-14 09:11 UTC, andrewvanderbyl commented on feng/ddc/src/cwg.py
> +    return [cwg + awgn]
Done.

2020-09-14 09:20 UTC, andrewvanderbyl commented on feng/ddc/src/cwg.py
>  def generate_complx_cw(cw_scale: float, freq: float, fs: int, num_samples: int, awgn_scale: float) -> np.ndarray:
Done.

2020-09-14 09:21 UTC, andrewvanderbyl commented on feng/ddc/src/ddc.py
> +    def __init__(self, decimation_factor: int, fs: int, ddc_coeff_filename: str) -> None:
Fixed.

2020-09-14 09:45 UTC, andrewvanderbyl commented on feng/ddc/testing/test_ddc.py
> +        )
Done.

2020-09-14 09:52 UTC, andrewvanderbyl commented on feng/ddc/src/ddc.py
> +    def _import_ddc_filter_coeffs(self, filename: str = "ddc_filter_coeffs_107.csv"):
Done. Used option 2.

2020-09-14 12:36 UTC, andrewvanderbyl commented on feng/ddc/testing/test_ddc.py
> +    assert ddc_channel[0][0] == expected_translation_center_channel
Modified as per above.

2020-09-14 12:36 UTC, andrewvanderbyl commented on feng/ddc/testing/test_ddc.py
> +    data = [cw1[0] + cw2[0]]
Fixed.

2020-09-14 12:36 UTC, andrewvanderbyl commented on feng/ddc/testing/test_ddc.py
> +    expected_translation_positive_band_edge = 503
Done.

2020-09-14 12:38 UTC, andrewvanderbyl commented on feng/ddc/testing/test_ddc.py
> +    assert dB_diff > 60
Done.

2020-09-15 07:19 UTC, andrewvanderbyl reviewed
Ok - Round to review. Go.

2020-09-15 07:19 UTC, andrewvanderbyl commented on feng/ddc/testing/test_cwg.py
> +
Nope. As I understand it, It's a negative frequency thing as the cw generated is complex (using e^(-j...)).When computing and plotting the complex fft, it is shown on an axis of 0 -> fs (where fs is the sampling freq), so for frequencies fs/2 -> fs, the 'negative' frequency is shown. That is why it is computed as fft_length - expected_bin. This is to look in the place numpy has placed it given the 0->fs x-axis.

2020-09-15 07:21 UTC, andrewvanderbyl commented
Changes made as per last PR comments. Review required.

2020-09-17 07:17 UTC, james-smith-za approved these changes
I'm going to say "approve".
I have made some fairly minor comments, which it's up to you whether to incorporate them or not. I would recommend that you do, but I won't block the work from going forward.

Overall, looking good!

2020-09-17 07:17 UTC, james-smith-za commented on feng/ddc/testing/test_ddc.py
>      mixing_freq = 100e6
I'd like tests to be documented a bit better. If there's a test-procedure document somewhere, then maybe a reference to the doc number, but if that's not the case (as with this PoC code) then some explanation for dummies as to why certain numbers were chosen. Not a whole undergrad textbook derivation, but I'd like to get a hand-wavy understanding if I read through it.

2020-09-17 07:45 UTC, andrewvanderbyl commented on feng/ddc/src/cwg.py
>          Sample rate for generated CW.
Done.

2020-09-17 07:46 UTC, andrewvanderbyl commented on feng/ddc/src/ddc.py
> +            Output array of complex-valued down-sampled data. Default decimate_offset = 0.
Done.

2020-09-17 07:47 UTC, andrewvanderbyl commented on feng/ddc/src/ddc.py
>          """Digital Down Conversion.
Fixed.

2020-09-17 08:03 UTC, andrewvanderbyl commented on feng/ddc/testing/test_ddc.py
>      mixing_freq = 100e6
Done.

2020-09-17 08:07 UTC, andrewvanderbyl commented
Thanks @james-smith-za for the comments. Changes made as requested. Merge pending review of @gcallanan.

2020-09-18 08:25 UTC, james-smith-za approved these changes

2020-09-21 11:24 UTC, andrewvanderbyl commented
All in agreement to merge.

2020-09-21 11:24 UTC, merged