NGC-230: Add scripts for calculating baselines and delay tracking requirements
ska-sa/dc_sand pull request #23
Opened 2021-07-12 18:31 UTC by tyronevb

This work was originally initiated in PR#20, but the original requestor is no longer with SARAO. To keep things clean and tidy, I'm raising a new pull request.

This adds a script to calculate the maximum baseline for a set of antennas that are described by their geographic coordinates. It then also uses this maximum baseline to calculate the delay tracking requirements.

I've refactored much of the original script and improved the usability of it. Also cleaned up the Python formatting (based on the pre-commit workflow and general best practices).

Contributes to: NGC-230

2021-07-13 05:25 UTC, james-smith-za requested changes

2021-07-13 05:25 UTC, james-smith-za commented on delay_tracking/README.md
> +(distance between antennas) and the second side is the wavefront. The third side is the delay. This is shown in the
I would say that the second side is parallel to the wavefront, rather than *is* the wavefront.

But also, the third side isn't the delay, because you can't have a triangle with one side measured in metres and another side measured in seconds.

I would say something to the effect of "the third side is a projection of the baseline length along the line normal to the the wavefront, or in the direction of the source of emission. The delay is the time that it takes the wavefront to travel this distance."

2021-07-13 05:25 UTC, james-smith-za commented on delay_tracking/README.md
> +The maximum delay occurs when the source is directly on the horizon: d<sub>max</sub> = d(0) = b cos(0)/c = b/c  (s)
Directly on the horizon is necessary but not sufficient - the maximum delay is when the source is on the horizon *and* directly in the direction that the baseline points. If it's on the horizon but the baseline is perpendicular to the direction of the source, then it's not much of a delay at all if any.

2021-07-13 05:25 UTC, james-smith-za commented on delay_tracking/delay_tracking_requirements_calculator.py
> +
Is the aim to release this to the general public, or to leave it only for internal use?
If the former, I'd suggest changing this just to "CBF Team" or some such.

2021-07-13 05:25 UTC, james-smith-za commented on delay_tracking/delay_tracking_requirements_calculator.py
> +        reader = csv.reader(csvfile, delimiter=delimiter)
`pandas` is also a good way to process CSV files.

No need for refactoring right now but if you're in the mood to learn something new, it's something to look into.

2021-07-13 05:25 UTC, james-smith-za commented on delay_tracking/delay_tracking_requirements_calculator.py
> +        baselines[ant_pair] = distance.GeodesicDistance(ant_a, ant_b).kilometers
So Geodesic distance is the distance along the surface of the Earth. Radio waves travel in straight lines though so if you want the true baseline lengths you'll need to calculate the chord length:
https://stackoverflow.com/questions/64584599/python-distance-in-miles-to-euclidean-distance-between-two-gps-coordinates

For scales as short as the MK+ ones (on the order of a few to tens of km) it shouldn't make a material difference to the results - it's not going to change how we specify the correlator in any way. But I think even if we don't change the code, we should put a note that if we start to move e.g. to SKA distances, we would want to be more accurate.

Though technically I think this is something that SE would do, not us.

2021-07-13 05:25 UTC, james-smith-za commented on delay_tracking/delay_tracking_requirements_calculator.py
> +    The angle between the third side and the baseline vector is equal to this elevation angle.
Same comment as what I said in the readme.

I'd avoid duplicating too much in terms of your documentation. It's just an opportunity for stuff to drift. I'd replace this paragraph with something like "See appropriate section in readme.md for further explanation" or some such.

2021-07-14 11:39 UTC, closed without merging

2021-07-19 08:45 UTC, tyronevb commented on delay_tracking/delay_tracking_requirements_calculator.py
> +
Changed `author` to "SARAO DSP Group"

2021-07-19 08:45 UTC, tyronevb commented on delay_tracking/delay_tracking_requirements_calculator.py
> +        reader = csv.reader(csvfile, delimiter=delimiter)
Yeah, I've used `pandas` before. But seems a bit overkill for this small dataset.

2021-07-19 08:49 UTC, tyronevb commented on delay_tracking/delay_tracking_requirements_calculator.py
> +        baselines[ant_pair] = distance.GeodesicDistance(ant_a, ant_b).kilometers
I had a similar discussion with Gareth when he initially put this together. We decided that using the Geodesic distance was sufficient for our purposes.

2021-07-19 08:53 UTC, james-smith-za commented on delay_tracking/delay_tracking_requirements_calculator.py
> +        baselines[ant_pair] = distance.GeodesicDistance(ant_a, ant_b).kilometers
That's fair - I'd just suggest adding a comment something to this effect:
```
# NOTE: Technically the distance that we want is a chord, not a geodesic. Geopy doesn't
# make it easy to get this though, and the difference is trivial on these distance scales, so
# we have opted to leave this as-is.
```

2021-07-19 08:58 UTC, tyronevb commented on delay_tracking/README.md
> +(distance between antennas) and the second side is the wavefront. The third side is the delay. This is shown in the
Have made some tweaks to this section based on the feedback but FWIW, I'm not the original author.

2021-07-19 09:01 UTC, tyronevb commented on delay_tracking/README.md
> +The maximum delay occurs when the source is directly on the horizon: d<sub>max</sub> = d(0) = b cos(0)/c = b/c  (s)
Added the second part of the criteria for maximum delay.

2021-07-19 09:03 UTC, tyronevb commented on delay_tracking/delay_tracking_requirements_calculator.py
> +        baselines[ant_pair] = distance.GeodesicDistance(ant_a, ant_b).kilometers
Agreed and added :)

2021-07-19 09:07 UTC, tyronevb commented on delay_tracking/delay_tracking_requirements_calculator.py
> +    The angle between the third side and the baseline vector is equal to this elevation angle.
Agreed and changed. Gareth's docstrings (as you know) are often a mixture of docstrings, theory and tutorial.