Prebeamform reorder
ska-sa/dc_sand pull request #28
Opened 2021-07-29 13:42 UTC by andrewvanderbyl

PR for prebeamform reorder. Two means to do CPU reordering included for consideration. All source files pass pre-commit workflow checks.

2021-08-02 10:12 UTC, james-smith-za requested changes
Gone over the logic, it makes sense.

The changes I've suggested will make for:
- less maintenance
- better consistency with existing code when this gets integrated, and
- more robustness

They're mostly aesthetic things, i.e. they won't affect the functionality as implemented now. But you'll thank me later I think.

2021-08-02 10:12 UTC, james-smith-za commented on feng/ddc/src/ddc_kernel.cu
>  #include <cuComplex.h>
I'd suggest doing a `git revert` to make a commit undoing your changes to these files, then adding that to this branch. Ping me if you aren't sure how to do that.

2021-08-02 10:12 UTC, james-smith-za commented on feng/ddc/testing/test_ddc.py
>  import pytest
Same comment. Don't want to include DDC stuff on this PR.

2021-08-02 10:12 UTC, james-smith-za commented on beamformer/test/prebeamform_reorder_test.py
> +
For instance, this looks like it comes from the old X-engine stuff. There's only one test here, so it's not relevant.

Bad / wrong documentation can be even worse than no documentation.

2021-08-02 10:12 UTC, james-smith-za commented on beamformer/test/prebeamform_reorder_test.py
> +    )
Have a look at how I've done the random data in the xbengine unit tests. It's recommended to give numpy a seed, so that we can run the unit tests the same way every time. You can also fill the input array in a way that is almost agnostic to what it looks like through introspection with numpy.

I think the pre-correlation reorder unit test would be the best one to look at.

2021-08-02 10:12 UTC, james-smith-za commented on beamformer/test/prebeamform_reorder_test.py
> +    )
Check my x-engine unit tests. You can get this from the template. That way if something in the template changes, you don't need to change this code as well. Less maintenance.

2021-08-02 10:12 UTC, james-smith-za commented on beamformer/test/prebeamform_reorder_test.py
> +    bufSamples_host = np.ndarray.view(bufSamples_host, dtype=np.uint16)
The second line is the proper way to do what you are doing in the first line.
```suggestion
    # Convert back to uint16 as to deal with the complex (real and imag) as single word pairs.
    bufSamples_host = np.ndarray.view(bufSamples_host, dtype=np.uint16)
```

In general, don't alter the dtype directly. It's bad practice. But if you use my suggestion from the precorrelation reorder unit test, you won't even need to do this because it'll be in the right format already.

2021-08-02 10:12 UTC, james-smith-za commented on beamformer/test/prebeamform_reorder_test.py
> +    ]
Best way to do something like this is to use numpy's `.empty_like()` function. Again, see my unit tests in xbgpu for an example.

The advantage to this is, if something changes (e.g. a dimension or whatever) you don't have to update the change in a dozen places, just one.

2021-08-02 10:12 UTC, james-smith-za commented on beamformer/test/prebeamform_reorder_test.py
> +    np.testing.assert_array_equal(viewed_cpu, viewed_gpu)
If they're the same data type to begin with, you can probably just test them for equality, you don't need to make a view.

But this problem goes away completely if you add a complexity dimension as I've suggested doing.

2021-08-02 11:25 UTC, andrewvanderbyl commented on beamformer/README.md
> +Input:  Data as ingest by an X-Engine core. This data is assumed to a subset of the full F-Engien output.
Fixed.

2021-08-02 11:29 UTC, andrewvanderbyl commented on beamformer/README.md
> +	uint16_t [n_batches][polarizations][n_channels] [times_per_block][samples_per_channel//times_per_block][n_ants]
Changed.

2021-08-02 11:37 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/kernels/prebeamform_reorder_kernel.mako
> + *             [n_samples_per_channel//times_per_block] [n_antennas]
This was kept to be consistent with naming in the precorrelation_reorder. I agree this could be renamed.

2021-08-02 11:43 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/kernels/prebeamform_reorder_kernel.mako
> +#define NR_STATIONS ${n_ants}
Changed.

2021-08-02 11:44 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/kernels/prebeamform_reorder_kernel.mako
> +#define bfNewIdxDBG 23352
Will be removed for merge.

2021-08-02 11:46 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/kernels/prebeamform_reorder_kernel.mako
> +        printf("blockIdx.y: %d\n", blockIdx.y);
Initially there was no ```blockIdx.y``` filtering so it was useful to know the value for y.

2021-08-02 12:02 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/kernels/prebeamform_reorder_kernel.mako
> +    iMatrixStride_y = iBatchCounter * NR_STATIONS * NR_CHANNELS * NR_SAMPLES_PER_CHANNEL * NR_POLARISATIONS;
Noted and fixed.

2021-08-02 12:12 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/kernels/prebeamform_reorder_kernel.mako
> +    iRemIndex = iThreadIndex_x % (NR_CHANNELS * NR_SAMPLES_PER_CHANNEL * NR_POLARISATIONS);
Noted and changed.

2021-08-02 12:15 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/kernels/prebeamform_reorder_kernel.mako
> +        u16TempSample = *(pu16ArrayReordered + bfNewIdx + iMatrixStride_y);
Debug will be removed.

2021-08-02 12:16 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/kernels/prebeamform_reorder_kernel.mako
> +}
Fixed.

2021-08-02 12:28 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +
Cleaned up.

2021-08-02 12:34 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +        """
Fixed.

2021-08-02 12:36 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +        # as and when the TensorCoreXEngine requires it.
Fixed.

2021-08-02 12:39 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +        # This 128 is hardcoded in the original Tensor Core kernel and (probably) has to do with
Fixed.

2021-08-02 12:43 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +        self.n_times_per_block = 128 // self._sample_bitwidth
Noted and fixed.

2021-08-02 13:29 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +    [n_batches][polarizations][n_channels] [times_per_block][samples_per_channel//times_per_block][n_ants]
Changed.

2021-08-02 13:31 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +        """Initialise the PreBeamformReorder object and specify the size of the memory buffers."""
Changed.

2021-08-02 13:36 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +        max_threadIdx = int(1024 * self.template.n_blocks_x)
Updated and made parameterizable. ```self.template.threads_per_block``` added in the template.

2021-08-02 13:36 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +            local_size=(1024, 1),
Updated and made parameterizable. ```self.template.threads_per_block``` added in the template.

2021-08-02 13:46 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/reorder.py
> +                        ]
Personally I prefer the little more easier to follow shortened name (i.e. `ant` instead of `a`), but to be consistent with other code I have changed it.

2021-08-02 13:49 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/reorder.py
> +    # output_data[:] = input_data.reshape(batches, ants, n_channel, -1, n_times_per_block, pols).transpose(0,5,2,3,4,1)
True. The nested for-loop has shown to execute in faster so I've left that in place.

2021-08-02 13:50 UTC, andrewvanderbyl commented on beamformer/requirements.txt
> +pybind11
Nope. Removed.

2021-08-02 13:50 UTC, andrewvanderbyl commented on beamformer/requirements.txt
> +ctypes
Nope. Removed.

2021-08-02 13:50 UTC, andrewvanderbyl commented on beamformer/requirements.txt
> +utils
Not anymore. Removed.

2021-08-02 14:04 UTC, andrewvanderbyl commented on beamformer/setup.py
> +        "Programming Language :: Python :: 3.6",
Changed.

2021-08-02 14:16 UTC, andrewvanderbyl commented on beamformer/test/prebeamform_reorder_test.py
> +
Fixed.

2021-08-02 14:21 UTC, andrewvanderbyl commented on beamformer/test/prebeamform_reorder_test.py
> +                                        f"output_data_cpu is {output_data_cpu[batch][pol][chan][tbs][sample][ant]} and bufReordered_host is {bufReordered_host[batch][pol][chan][tbs][sample][ant]}: ba
Changed.

2021-08-02 14:41 UTC, andrewvanderbyl commented on beamformer/test/prebeamform_reorder_test.py
> +"""
Fixed.

2021-08-02 14:54 UTC, andrewvanderbyl commented on beamformer/test/test_parameters.py
> +Module containing correlator configuration options that should be tested where appropriate in all unit tests.
Changed.

2021-08-02 15:07 UTC, andrewvanderbyl commented on beamformer/requirements.txt
> +typing
Removed.

2021-08-02 15:10 UTC, andrewvanderbyl commented on feng/ddc/src/ddc_coeff_107MHz.csv
> +8.392333984375e-05,4.57763671875e-05,5.340576171875e-05,6.103515625e-05,6.866455078125e-05,7.62939453125e-05,7.62939453125e-05,7.62939453125e-05,7.62939453125e-05,6.103515625e-05,4.57763671875e-05,2.
I have no idea! I didn't commit these for this PR.

2021-08-03 07:49 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/kernels/prebeamform_reorder_kernel.mako
> + *    uint16_t [n_batches][polarizations] [n_channels] [times_per_block] [n_samples_per_channel//times_per_block]
Changed.

2021-08-03 08:30 UTC, james-smith-za commented on beamformer/test/prebeamform_reorder_test.py
> +    np.testing.assert_array_equal(viewed_cpu, viewed_gpu)
I might have. If the arrays have different dtypes, then a view is the correct way to change them to match.

However, if they already have the same dtype, then doing this isn't particularly useful - you can just compare the uint16 values directly.

As I said - if you introduce the `complexity` dimension, then this becomes moot and you won't need to change dtypes anymore.

2021-08-03 09:05 UTC, andrewvanderbyl commented on beamformer/test/prebeamform_reorder_test.py
> +    )
About 20 lines above the template is instantiated which uses the runtime parameters as passed by pytest. These same parameters are used in creating the input and out shapes. Is this not correct?

2021-08-03 12:29 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +            accel.Dimension(self.n_polarisations, exact=True),
Complexity dimension added.

2021-08-03 12:30 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +            dimensions=self.template.inputDataShape, dtype=np.uint16
Complexity Dimension added.

2021-08-03 12:33 UTC, andrewvanderbyl commented on beamformer/test/prebeamform_reorder_test.py
> +    )
Random number with seeding added.

2021-08-03 12:35 UTC, andrewvanderbyl commented on beamformer/test/prebeamform_reorder_test.py
> +    bufSamples_host = np.ndarray.view(bufSamples_host, dtype=np.uint16)
Removed.

2021-08-03 12:37 UTC, andrewvanderbyl commented on beamformer/test/prebeamform_reorder_test.py
> +    ]
Fixed using bufSamples_host.shape and bufReordered_host.shape.

2021-08-03 12:46 UTC, andrewvanderbyl commented on beamformer/test/prebeamform_reorder_test.py
> +    np.testing.assert_array_equal(viewed_cpu, viewed_gpu)
Removed and assert applied directly to cup and gpu output arrays.

2021-08-04 08:39 UTC, james-smith-za requested changes
Much better but still some outstanding issues. Mainly around variable naming - the logic is correct, but the name can be confusing.

2021-08-04 08:39 UTC, james-smith-za commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +        """Initialise the PreBeamformReorderTemplate class and compile the pre-beamform reorder kernel."""
You can just remove the docstring here completely if you want. As I said, `__init__` has a clearly-defined meaning in Python, so there's no need to document it (unless you do something funky here which the developer might not expect).

2021-08-04 08:39 UTC, james-smith-za commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +        # n_blocks is hardcoded to 16 and initially started with the tensor core X-Engine kernel and it has shown to allow for efficient thread block size.
Much better. I think that this should just be `n_samples_per_block` for reasons stated above.

2021-08-04 08:39 UTC, james-smith-za commented on beamformer/README.md
> +	uint16_t [n_batches][polarizations][n_channels] [blocks][samples_per_channel//blocks][n_ants]
Having thought about this a bit more though, is the description actually true? I think two of your indices are backwards:

```suggestion
	uint16_t [n_batches][polarizations][n_channels][blocks][samples_per_block][n_ants]
	where blocks = samples_per_channel//samples_per_block
```

If you compare the order of dimensions here to the order that they are (currently) stated in line 69-77 of prebeamformreorder.py - those are in the right order.

2021-08-04 08:39 UTC, james-smith-za commented on beamformer/beamform_reorder/kernels/prebeamform_reorder_kernel.mako
> +#define NR_BLOCKS ${n_blocks}
I also don't think `NR_BLOCKS` is correct, I think it's actually `NR_SAMPLES_PER_BLOCK`.

The 16 that was previously called `n_times_per_block` isn't the number of blocks that the data gets chopped into, but rather the size of the blocks, they each get 16 samples.

2021-08-04 08:39 UTC, james-smith-za commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +            accel.Dimension(self.n_samples_per_channel // self.n_blocks, exact=True),
So you see this looks like `samples_per_channel // n_blocks` means that you'd get a varying number of samples per block. But you don't, it's 16, it's the number of blocks that varies (i.e. the size of **this** dimension).

2021-08-04 08:39 UTC, james-smith-za commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +    In 8-bit input mode n_blocks is equal to 16.
More duplication of documentation. In fact, perhaps the best place to have it would probably be in the docstring here, and in your readme and elsewhere, just refer to this class's documentation.

2021-08-04 08:39 UTC, james-smith-za commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +        max_threadIdx = int(self.template.threads_per_block * self.template.n_blocks_x)
Perfect.

2021-08-04 08:39 UTC, james-smith-za commented on beamformer/beamform_reorder/reorder.py
>          Number of blocks to break the number of samples per channel into.
Having looked at this again now - I think this description was wrong to begin with. `n_times_per_block` isn't the number of blocks, it describes the size of the blocks. The number of them depends on `samples_chan` above.

2021-08-04 08:39 UTC, james-smith-za commented on beamformer/requirements.txt
> +katsdpsigproc[CUDA] @ git+https://github.com/ska-sa/katsdpsigproc
```suggestion
katsdpsigproc[CUDA]
```
You can keep it in, but if you remove the `@git` part, then it'll get the latest release from pip.

2021-08-04 08:39 UTC, james-smith-za commented on beamformer/test/prebeamform_reorder_test.py
> +      uint16_t [n_batches][polarizations][n_channels] [n_blocks][samples_per_channel//n_blocks][n_ants]
I think this is an ideal place to refer to the docstring of the class itself.

2021-08-04 08:39 UTC, james-smith-za commented on beamformer/test/prebeamform_reorder_test.py
>          - This is limited to a batch of one, as the CPU-side verification takes some time to complete.
I don't think this "batch of one" comment is valid anymore? You test a parameterised number of batches?

2021-08-04 08:39 UTC, james-smith-za commented on beamformer/test/prebeamform_reorder_test.py
>          Number of blocks to break the number of samples per channel into.
Also incorrect.

2021-08-04 08:39 UTC, james-smith-za commented on beamformer/test/prebeamform_reorder_test.py
> +        4. Verify it relative to the input array.
This is good information to go in the test's documentation, but some small suggestions regarding correctness.
```suggestion

    This test:
        1. Populate a host-side array with random data in the range of the relevant dtype.
        2. Instantiate the prebeamformer_reorder_kernel and pass this input data to it.
        3. Grab the output, reordered data.
        4. Verify it relative to the input array using a reference computed on the host.
```

The numerical range that you specified was correct for uint16, but not currently. It'll now assign [-128; 127) range numbers which int8 numbers can hold. The advantage to being a bit more vague and generic is that we don't need to update the docstrings (and avoid drifting out of sync) if we decide later to go to say 16-bit.

2021-08-04 08:39 UTC, james-smith-za commented on beamformer/test/prebeamform_reorder_test.py
> +    #np.testing.assert_array_equal(viewed_cpu, viewed_gpu)
Rather just remove, no need to comment-out.

2021-08-04 09:21 UTC, andrewvanderbyl commented on beamformer/requirements.txt
> +katsdpsigproc[CUDA] @ git+https://github.com/ska-sa/katsdpsigproc
Fixed.

2021-08-04 09:40 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/kernels/prebeamform_reorder_kernel.mako
> + *    uint16_t [n_batches][polarizations][n_channels] [n_blocks][samples_per_channel//n_blocks][n_ants]
Fixed.

2021-08-04 09:44 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/kernels/prebeamform_reorder_kernel.mako
> +#define ANTENNAS ${n_ants}
Fixed.

2021-08-04 09:50 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/kernels/prebeamform_reorder_kernel.mako
> + *   - uint16_t [n_batches][polarizations][n_channels] [n_blocks][samples_per_channel//n_blocks][n_antennas]
Merged docstrings and reworded to be different.

2021-08-04 09:51 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +        """Initialise the PreBeamformReorderTemplate class and compile the pre-beamform reorder kernel."""
Removed.

2021-08-04 09:54 UTC, andrewvanderbyl commented on beamformer/test/prebeamform_reorder_test.py
>          - This is limited to a batch of one, as the CPU-side verification takes some time to complete.
Removed.

2021-08-04 09:57 UTC, andrewvanderbyl commented on beamformer/test/prebeamform_reorder_test.py
> +        4. Verify it relative to the input array.
Noted and fixed.

2021-08-04 09:58 UTC, andrewvanderbyl commented on beamformer/test/prebeamform_reorder_test.py
> +    #np.testing.assert_array_equal(viewed_cpu, viewed_gpu)
Removed.

2021-08-04 11:47 UTC, andrewvanderbyl commented on beamformer/README.md
> +	uint16_t [n_batches][polarizations][n_channels] [blocks][samples_per_channel//blocks][n_ants]
Spaces removed. I have changed the line to:
```suggestion
	uint16_t [n_batches][polarizations][n_channels] [blocks][samples_per_channel//blocks][n_ants]
```

2021-08-04 11:56 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/kernels/prebeamform_reorder_kernel.mako
> +#define NR_BLOCKS ${n_blocks}
Agreed. This was incorrect in this context.

2021-08-04 11:58 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +        # n_blocks is hardcoded to 16 and initially started with the tensor core X-Engine kernel and it has shown to allow for efficient thread block size.
See changes made. outputDataShape modified to only use `n_blocks` and `n-samples_per_block`

2021-08-04 15:03 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +        """Initialise the PreBeamformReorderTemplate class and compile the pre-beamform reorder kernel."""
Turns out I have to have a docstring or the style checkers fail.

2021-08-05 06:05 UTC, james-smith-za requested changes
I disagree regarding the block-size issue, but the rest looks good.

Let me know if you want to jump on zoom to discuss it.

2021-08-05 06:34 UTC, james-smith-za commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +        """Initialise the PreBeamformReorderTemplate class and compile the pre-beamform reorder kernel."""
That's odd. Your `pydocstyle.ini` should look like this:
```
[pydocstyle]
# - D105 tells pydocstyle to ignore magic methods. These have standard meanings,
#   so we needn't document them.
# - D107 tells pydocstyle to ignore __init__ methods. Since we document the
#   class itself, repeating things in the __init__ method adds no value and
#   potentially introduces opportunity for redundant documentation to drift out
#   of sync.
# - We use "add-ignore" instead of "ignore" because "ignore" overrides the
#   defaults (which are relatively sane), "add-ignore" just adds to them.
add-ignore = D105,D107
```
Try `pre-commit install` again?

2021-08-05 09:51 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +        self.n_samples_per_block = n_samples_per_channel // self.n_blocks
Updated made and adjusted:
self.n_samples_per_block = 128 // self._sample_bitwidth
and 
self.n_blocks = self.n_samples_per_channel // self.n_samples_per_block

2021-08-05 10:39 UTC, james-smith-za commented on beamformer/beamform_reorder/prebeamform_reorder.py
> +        self.n_blocks = self.n_samples_per_channel // self.n_samples_per_block
```suggestion
        # This 128 is hardcoded in the original tensor core correlation kernel to allow for efficient thread-block size
        self.n_samples_per_block = 128 // self._sample_bitwidth
        self.n_blocks = self.n_samples_per_channel // self.n_samples_per_block
```

Just updating the comment to reflect the actual state that the code is in.

2021-08-05 11:51 UTC, james-smith-za approved these changes
Looking good. I'm happy.

2021-08-05 11:54 UTC, merged