Beamforming
ska-sa/dc_sand pull request #30
Opened 2021-09-07 10:11 UTC by andrewvanderbyl

First PR for beamforming branch. This includes two approaches to the complex multiplication:
1) cublasSgemm
2) Numba-based kernel

It should be noted that implementation 2) is not optimised to use shared memory and was a proof-of-concept.

2021-09-08 15:23 UTC, james-smith-za requested changes
It seems to me that one assumption you are making here is that the B matrix in the multiply operation already has the twiddle necessary to make the complex multiply work.

This approach can work, but you'd probably need to prepare the matrix in the reorder stage. Another, slightly more bandwidth-friendly alternative may be to handle that in shared memory to save global memory bandwidth, the way that JR does in the TCC kernel.

Also I couldn't quite make out whether you were using the steering coefficients as the A or the B matrix (granted I didn't put too much effort into this). I don't have my notebooks with me and I can't recall what I decided when I looked at this about a year ago. It's just something that you might want to get clear.

Other than that - it looks as though you've got the idea with the OperationSequence - which was one of the main objectives of the exercise. If you have that down, the rest is implementation details which can be panel-beaten as time goes on.

2021-09-08 15:23 UTC, james-smith-za commented on beamformer/scratch/multiply.py
> +import numpy as np
I know this is the scratch directory but some documentation saying what this was for, and what you learned from it maybe.

2021-09-09 11:32 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/kernels/prebeamform_reorder_kernel.mako
> +#define iThreadDBG 0
Noted. This particular  #define is for debug so can be removed.

2021-09-09 11:33 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/kernels/prebeamform_reorder_kernel.mako
> +#define iThreadDBG 0
Updated in the interim for consistency.

2021-09-09 11:35 UTC, andrewvanderbyl commented on beamformer/beamform_reorder/kernels/prebeamform_reorder_kernel.mako
> +        }
Removed.

2021-09-09 13:31 UTC, andrewvanderbyl commented on beamformer/test/beamform_mult_kernel_test.py
> +        )
Initially I was testing with ones so it made life easier. This has been changed.

2021-09-09 14:02 UTC, andrewvanderbyl commented on beamformer/test/beamform_mult_kernel_test.py
> +    cpu_coeffs = coeff_gen.CPU_Coeffs()
This should probably be discussed, but the reason is due to matrix requirements for computation. The GPU kernel version uses the complex multiplication additional dimension trick, where the cpu verification uses numpy and requires the <real, imag> data to be interleaved. This could be joined into one method but the matrices have to be different.

2021-09-10 06:37 UTC, james-smith-za commented on beamformer/test/beamform_mult_kernel_test.py
> +    cpu_coeffs = coeff_gen.CPU_Coeffs()
Yeah. For the time being, proof-of-concept stuff, it may be ok. But for what we actually deploy, we will want to unify things. Let's put it on the agenda for discussion at some point.

2021-09-13 08:43 UTC, andrewvanderbyl commented on beamformer/test/beamform_mult_kernel_test.py
> +                        coeffs[i, j, k] = real_value
Corrected. Turns out the order was swapped and numpy dot product selected was the conjugate version. For-loop removed as suggested.

2021-09-13 13:01 UTC, andrewvanderbyl commented on beamformer/beamforming/complex_mult_cpu.py
> +@jit
Seems numba deprecation warnings are related to the use of @jit. @njit fails as `nopython=True` mode doesn't support some of the code requirements. Online suggestions and experimentation suggests the removal of @jit for coeff generation as it may be faster without. This has been tested and pytest does compute faster without @jit in these cases (and numba deprecation warning related to `nopython=True` mode are gone.

2021-09-16 12:29 UTC, james-smith-za requested changes

2021-09-16 12:29 UTC, james-smith-za commented on beamformer/beamforming/beamform_op_sequence.py
> +
Rather remove commented out code.

2021-09-16 12:29 UTC, james-smith-za commented on beamformer/beamforming/beamform_op_sequence.py
> +        test_id,
Add this parameter to your docstring. Docstring still doesn't quite match the actual paramters list.

2021-09-16 12:29 UTC, james-smith-za commented on beamformer/beamforming/beamform_op_sequence.py
> +    def __init__(self, template, queue, test_id):
Docstring doesn't match parameters...

Bruce also reminds me that he has an informal convention of documenting the slots of an `OperationSequence` - see here: https://github.com/ska-sa/katgpucbf/blob/4cf82f3f1b12916d6044e39486c8a535d7d2a6b2/src/katgpucbf/fgpu/postproc.py#L53-L61

2021-09-16 12:29 UTC, james-smith-za commented on beamformer/beamforming/beamform_op_sequence.py
>  if __name__ == "__main__":
Are you still using the stuff here, or are you relying on pytest?

2021-09-16 12:29 UTC, james-smith-za commented on beamformer/beamforming/complex_mult_kernel.py
> +# from numba import jit
Rather remove instead of leaving commented-out code lying around. It's there in the git history if you need to go back and get it.

2021-09-16 12:29 UTC, james-smith-za commented on beamformer/beamforming/matrix_multiply.py
> +        test_id,
Also missing from the docstring.

Aside from this, this docstring is correct - right parameters, in order. Thanks.

Feel free to ignore these `test_id` parameters from the docstring if you're intending to remove them before actually merging though.

2021-09-16 12:29 UTC, james-smith-za commented on beamformer/unit_test/__init__.py
> +__all__ = ["coeff_generator", "complex_mult_cpu"]
I prefer this to how it used to be.

Don't make any changes now, but for future, when you're using something only in the unit testing (and not anywhere in actual "useful" code), then look at making a pytest fixture for it. But don't worry about that just yet, just note it away for next time you feel like extending your toolkit.

2021-09-16 12:29 UTC, james-smith-za commented on mypy.ini
> +ignore_errors = True
Does this ... effectively just turn off mypy?

2021-09-16 14:34 UTC, andrewvanderbyl commented on beamformer/beamforming/beamform_op_sequence.py
>  if __name__ == "__main__":
This has been left intentionally - it serves as a backup means to run the test if `pytest` has another issue (which was experienced recently - pytest didn't resolve some of the imports). Having this made it easier to debug.

2021-09-16 14:42 UTC, andrewvanderbyl commented on mypy.ini
> +ignore_errors = True
It think it only applies to the files in the folder listed for exclusion. I think!

2021-09-16 15:38 UTC, andrewvanderbyl commented
Changes made. Mostly docstring fixes.

2021-09-20 15:42 UTC, james-smith-za requested changes
Small nitpicks now. Coming along nicely.

2021-09-20 15:42 UTC, james-smith-za commented on beamformer/beamforming/beamform_op_sequence.py
> +    def __init__(self, template, queue, test_id):
You marked this as resolved, but it looks unchanged to me?

I'd expect to see a docstring something like this based on `__init__()`'s arguments:
```
"""Operation sequence linking reorder and matrix multiplication to implement beamforming.

Parameters
-----------
template
    The template for this operation sequence.
queue
    GPU command queue that we are going to work on.
test_id
    Temporary test parameter.
"""
```

2021-09-21 08:10 UTC, andrewvanderbyl commented on beamformer/beamforming/beamform_op_sequence.py
> +
I'm not seeing this change. Are you sure you are looking at the correct version?

2021-09-21 08:37 UTC, andrewvanderbyl commented
Updated docstrings as requested. I think that was all the changes requested.

2021-09-21 09:58 UTC, james-smith-za approved these changes

2021-09-21 11:06 UTC, merged