Sphinx doc MWE
ska-sa/dc_sand pull request #52
Opened 2022-06-27 12:37 UTC by james-smith-za

If you type `make latexpdf` then it spits out a PDF like this:
[without modification.pdf](https://github.com/ska-sa/dc_sand/files/8991994/without.modification.pdf)

If you just do `make latex` and then fiddle with the `.tex` file a bit, then you can get this:
[hacked.pdf](https://github.com/ska-sa/dc_sand/files/8991997/hacked.pdf)
which I think is quite good.

Which reminds me, I should document the above in a readme...

2022-06-28 13:55 UTC, bmerry commented
I'm busy reviewing this now. I have a (very hacky) idea for automating the correct placement of references but need to try it out and dust off my low-level TeX skills.

2022-06-28 14:58 UTC, bmerry requested changes

2022-06-28 14:58 UTC, bmerry commented on sphinx_design_doc_mockup/conf.py
> +\lstset{postbreak=\raisebox{0ex}[0ex][0ex]{\ensuremath{\hookrightarrow\space}}}
Do we necessarily want this off the bat? We used it in the qual report because it has gobs of random test output dumped into the report, but we probably shouldn't have much if any code in a high-level design doc.

2022-06-28 14:58 UTC, bmerry commented on sphinx_design_doc_mockup/conf.py
> +\usepackage{mathtools}
Are we using this for anything?

2022-06-28 14:58 UTC, bmerry commented on sphinx_design_doc_mockup/conf.py
> +\usepackage{colortbl}
What does this do?

2022-06-28 14:58 UTC, bmerry commented on sphinx_design_doc_mockup/conf.py
> +latex_elements["maketitle"] = "\\makekatdocbeginning"
```suggestion
latex_elements["maketitle"] = r"\makekatdocbeginning"
```

2022-06-28 14:58 UTC, bmerry commented on sphinx_design_doc_mockup/conf.py
> +latex_additional_files = ["katdoc.sty", "sarao_logo.png"]
What about the other images?

2022-06-28 14:58 UTC, bmerry commented on sphinx_design_doc_mockup/conf.py
> +    preamble += f"\t\\addcontributor{{{role}}}{{{name}}}{{{designation}}}{{{affiliation}}}{{{date}}}\n"
Do we get much benefit from putting this all this information into Python variables and then translating it to LaTeX, rather than just writing the LaTeX? Either way there is some block of text that needs editing with document-specific information.

2022-06-28 17:55 UTC, andrewvanderbyl commented on sphinx_design_doc_mockup/conf.py
> +    ("A", "01 January 1970", "N/A", "Initial release for internal review."),
Do we want to keep doc history on a conf file? I would think that should be part of the top level document as it is document specific.

2022-06-28 18:21 UTC, andrewvanderbyl commented
Not having any experience with Sphinx it's difficult to comment on specifics. In general this looks good but my two concerns still stand a)that this approach is not collaborative friendly if working on the same doc simultaneously with another person; b) it means another typeset language and it's nuances which can easily consume vast quantities of time to get things 'just right'. Again, we need to ask if the benefit of such an approach out merits the simpler Google Doc approach. As an aside - I see there is a Google Doc plugin that can handle LaTeX directly in the GD if one wants to do good looking equations etc. (not limited to that). I do see merit in this sort of auto document creation for qualifying tests though.

2022-06-29 08:52 UTC, james-smith-za commented on sphinx_design_doc_mockup/conf.py
> +release = "B"
Oops.

2022-06-29 08:53 UTC, james-smith-za commented on sphinx_design_doc_mockup/conf.py
> +    ("A", "01 January 1970", "N/A", "Initial release for internal review."),
That's a fair point but this conf file is also doc-specific, you'd need a separate one for every document you're generating.

Well kind of, it's possible to use Sphinx to generate a bunch of related documents in the same batch, but I'm not sure we'd really want to go down that route.

2022-06-29 08:55 UTC, james-smith-za commented on sphinx_design_doc_mockup/conf.py
> +latex_additional_files = ["katdoc.sty", "sarao_logo.png"]
Interestingly it worked without them being here. I suspect that may be because `sarao_logo.png` is only referred in the raw latex preamble, not in the actual rst text that Sphinx itself parses.

2022-06-29 09:18 UTC, james-smith-za commented on sphinx_design_doc_mockup/conf.py
> +\usepackage{mathtools}
It's an extension of amsmath, and I think it makes stuff look better. I don't have extensive mathematics in this particular example, but there's a fair chunk of it in the concept design doc, especially around delay tracking.

2022-06-29 09:18 UTC, james-smith-za commented on sphinx_design_doc_mockup/conf.py
> +\usepackage{colortbl}
I wanted to colour in blocks on a table at some point, I don't think we need that here. I can remove it.

2022-06-29 09:20 UTC, james-smith-za commented on sphinx_design_doc_mockup/conf.py
> +# This is going to take a bit of building up.
I'm ... not vehemently opposed to this, but .sty files have different behaviour from normal TeX files in a way that I've never really taken the time to understand. Which is the main reason that I haven't done something like that.

2022-06-29 09:25 UTC, james-smith-za commented on sphinx_design_doc_mockup/conf.py
> +    preamble += f"\t\\addcontributor{{{role}}}{{{name}}}{{{designation}}}{{{affiliation}}}{{{date}}}\n"
I feel as though it's more user-friendly to update Python variables at the top of the file and then ignore the bottom part while it does its thing. It's easier to make comments that stand out with a text editor in Python, because the LaTeX is in a monochromatic raw string, it's harder for the eye to pick things out.

But I'm not vehemently opposed to changing if there's strong disagreement.

2022-06-29 09:37 UTC, bmerry commented on sphinx_design_doc_mockup/conf.py
> +latex_additional_files = ["katdoc.sty", "sarao_logo.png"]
Right, now that I read the [documentation](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-latex_additional_files) it makes sense.

2022-06-29 09:46 UTC, james-smith-za commented on sphinx_design_doc_mockup/conf.py
> +\renewcommand{\floatpagefraction}{0.8}
It's explained here: https://tex.stackexchange.com/questions/39017/how-to-influence-the-position-of-float-environments-like-figure-and-table-in-lat/39020#39020

More cargo-culting, it was probably originally a style thing. It doesn't appear to make a difference to this particular example, so I have removed it.

2022-06-29 09:49 UTC, bmerry commented on sphinx_design_doc_mockup/conf.py
> +# This is going to take a bit of building up.
I don't think anything stops you from just putting stuff in a .sty file that you'd put in a normal preamble. It's just that typical .sty files use all the deep TeX voodoo.

2022-06-29 10:02 UTC, james-smith-za commented on sphinx_design_doc_mockup/conf.py
> +    preamble += f"\t\\addcontributor{{{role}}}{{{name}}}{{{designation}}}{{{affiliation}}}{{{date}}}\n"
That could work. Something like 
``` python
latex_elements["preamble"] = r"\input{some_latex.tex}"
```
and then include that in `latex_additional_files`.

2022-06-29 13:04 UTC, james-smith-za commented on sphinx_design_doc_mockup/katdoc.sty
> +            \multirow{6}{*}{\begin{tabular}[c]{@{}l@{}}Physical /\\Postal \\ Address\end{tabular}} & ??? & Black River Park North & P.O. Box 443, & Posbus 69, \\
Sigh... it really should, but I'm not sure whether we have an actual address in Jo'burg just yet.

2022-06-29 13:07 UTC, james-smith-za commented on sphinx_design_doc_mockup/katdoc.sty
> +\usetikzlibrary{patterns,shapes.arrows}
Does Sphinx not do that if we include tikz figures in the code? I think the fgpu documentation has your big flowchart which we had to add a couple of lines to the `conf.py` for IIRC.

2022-06-29 13:08 UTC, james-smith-za commented on sphinx_design_doc_mockup/conf.py
> +# This is going to take a bit of building up.
Let me give that a try.

2022-06-30 08:17 UTC, bmerry commented on sphinx_design_doc_mockup/katdoc.sty
> +\usetikzlibrary{patterns,shapes.arrows}
I checked the sphinxcontrib-tikz docs again: you just need to set `tikz_tikzlibraries` in conf.py. Which makes me question whether we actually need to put anything to do with tikz or pgfplots into this preamble.

2022-07-01 07:26 UTC, bmerry requested changes
Looks good apart from one typo and a question about E501. I like the much shorter conf.py.

I think I'm still leaning towards thinking that working directly in LaTeX may be better IF the whole team is familiar with it. While it can be a pain, that'll mostly be in setting up the template (and probably less of a pain than trying to hack things to get the bibliography in the right place), and once we're filling in content sections I don't think there will be any big advantage to Sphinx, and potentially disadvantages since we won't easily be able to take advantage of advanced packages in LaTeX.

One advantage of using Sphinx is that we've already written a lot of design documentation in it.

2022-07-01 07:26 UTC, bmerry commented on .flake8
> +    sphinx_design_doc_mockup/conf.py: E501,
Is this still the case? I haven't counted but nothing looks particularly long by eyeball.

2022-07-01 07:26 UTC, bmerry commented on sphinx_design_doc_mockup/conf.py
> +today_fmt = "%d %b %Y"
RIP ISO 8601.

2022-07-01 07:26 UTC, bmerry commented on sphinx_design_doc_mockup/conf.py
> +# list should be a single tupele.
```suggestion
# list should be a single tuple.
```

2022-07-01 09:45 UTC, james-smith-za commented on sphinx_design_doc_mockup/conf.py
> +today_fmt = "%d %b %Y"
Well, most of the documents that I have seen in circulation in SARAO seem to prefer "14 February 2022" over "2022-02-14".

I'm not a fanaticist about this, I prefer having the month name spelled out fully, but it depends on the organisation's recommended style I guess. It doesn't need to be machine-readable.

2022-07-01 09:48 UTC, james-smith-za commented
> I think I'm still leaning towards thinking that working directly in LaTeX may be better IF the whole team is familiar with it.
True, but:
> One advantage of using Sphinx is that we've already written a lot of design documentation in it.
so ... swings and roundabouts I guess.

> once we're filling in content sections I don't think there will be any big advantage to Sphinx, and potentially disadvantages since we won't easily be able to take advantage of advanced packages in LaTeX.

In some ways, restricting the use of advanced packages can be an advantage, it'll almost enforce keeping things simpler.

All that being said, I agree the ultimate decision isn't actually an obvious one.

2022-07-01 09:58 UTC, bmerry commented on sphinx_design_doc_mockup/conf.py
> +today_fmt = "%d %b %Y"
It was a tongue-in-cheek comment.

2022-07-01 09:59 UTC, bmerry approved these changes

2022-07-04 06:02 UTC, tyronevb approved these changes
The generated document looks good. I don't see too many advantages being offered by this over just using LaTeX and a Git repository. Assuming most of the team is more comfortable (and suitably proficient) with  LaTeX, I'm going to strongly suggest we rather go that route. If collaboration through Git isn't ideal or intuitive, for documentation that is, we could consider adopting a platform like [Overleaf](https://www.overleaf.com/). It'll cost a little money, but still less than Office 365.

2022-07-04 07:31 UTC, merged